// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtuJaegf4WAoaXh9twZdubseIVnaRrIr0',
    appId: '1:225798190103:web:d0082969cbfdbad3661852',
    messagingSenderId: '225798190103',
    projectId: 'roadifyy',
    authDomain: 'roadifyy.firebaseapp.com',
    storageBucket: 'roadifyy.firebasestorage.app',
    databaseURL:
        'https://roadifyy-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLfTfxJoB0t9rVDOYvt9ivH0A5Ncoh-3s',
    appId: '1:225798190103:android:1a003298f7eca771661852',
    messagingSenderId: '225798190103',
    projectId: 'roadifyy',
    storageBucket: 'roadifyy.firebasestorage.app',
    databaseURL:
        'https://roadifyy-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtuJaegf4WAoaXh9twZdubseIVnaRrIr0',
    appId: '1:225798190103:web:005ad43488422167661852',
    messagingSenderId: '225798190103',
    projectId: 'roadifyy',
    authDomain: 'roadifyy.firebaseapp.com',
    storageBucket: 'roadifyy.firebasestorage.app',
    databaseURL:
        'https://roadifyy-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
}
