name: Build Flutter APK

on:
  push:
    branches: [ "main" ]   # build APK whenever you push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.4'
          channel: 'stable'

      # Step 3: Install dependencies
      - name: Get dependencies
        run: flutter pub get

      # Step 4: Build APK
      - name: Build release APK
        run: flutter build apk --release

      # Step 5: Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
